/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package janelas.sistema;

import classes.Categoria;
import classes.Filme;
import classes.Nota;
import classes.Usuario;
import java.util.ArrayList;
import java.util.HashMap;

import sistemacatalogofilmes.SistemaCatalogoFilmes;

/**
 *
 * @author Admin
 */
public class frmRecomendacoes extends javax.swing.JFrame {

    /**
     * Creates new form frmRecomendacoes
     */
    public frmRecomendacoes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRecomendacao = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbmPopular = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Baseado nos seus gostos:");

        tblRecomendacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblRecomendacao);

        jLabel2.setText("Populares entre os usuários:");

        tbmPopular.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbmPopular);

        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(15, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(416, 367));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        HashMap<Categoria, Integer> minhasCategorias = new HashMap<>();
        HashMap<Filme, Integer> hmFilmesQtd = new HashMap<>();
        HashMap<Filme, Integer> hmFilmesNotas = new HashMap<>();
        HashMap<Filme, Float> hmFilmesMedias = new HashMap<>();
        ArrayList<Filme> filmesAssistidos = new ArrayList<>();
        Usuario eu = SistemaCatalogoFilmes.usuarioLogado;
        
        int i;
        for ( i=0; i < SistemaCatalogoFilmes.bancoNotas.size(); i++) {
            Nota nota = SistemaCatalogoFilmes.bancoNotas.get(i);
            
            // Adiciona a minha lista de assistidos, e a categoria
            if ( nota.getUsuario().equals( eu ) ) {
                // Add assistidos
                filmesAssistidos.add(nota.getFilme());
                
                // Add Categorias
                int j;
                for ( j=0; j < nota.getFilme().getCategorias().size(); j++) {
                    if ( minhasCategorias.containsKey(nota.getFilme().getCategorias().get(j)) ) {
                        minhasCategorias.replace(nota.getFilme().getCategorias().get(j), minhasCategorias.get(nota.getFilme().getCategorias().get(j)) + 1);
                    } else {
                        minhasCategorias.put(nota.getFilme().getCategorias().get(j), 1);
                    }
                }
            } 
            // Senão foi uma nota que eu dei, adiciono a lista de possoveis recomendações
            else {
                // Testa se o filme já está na lista
                if ( hmFilmesQtd.containsKey(nota.getFilme()) ) {
                    hmFilmesQtd.replace(nota.getFilme(), hmFilmesQtd.get(nota.getFilme()) + 1);
                    hmFilmesNotas.replace(nota.getFilme(), hmFilmesNotas.get(nota.getFilme()) + nota.getNota());
                } else {
                    hmFilmesQtd.put(nota.getFilme(), 1);
                    hmFilmesNotas.put(nota.getFilme(), nota.getNota());
                }
            }
            
        }
        
        // Nesse ponto já tenho todas as notas e categorias
        // Calculo as médias
        for ( i=0; i < SistemaCatalogoFilmes.filmes.size(); i++ ) {
            
        }
        
        String colunas[] = { "Código", "Nome", "Média" };
        String dados[][];
        ArrayList<Nota> temp = new ArrayList<>();
        int i;
        
        for (i=0; i < SistemaCatalogoFilmes.bancoNotas.size(); i++ ) {
            if ( SistemaCatalogoFilmes.bancoNotas.get(i).getFilme().equals(filme) ) {
                temp.add( SistemaCatalogoFilmes.bancoNotas.get(i) );
            }             
        }
        
        dados = new String[temp.size()][colunas.length];
        for (i=0; i < temp.size(); i++ ) {
            dados[i][0] = temp.get(i).getUsuario().getNome();
            dados[i][1] = String.valueOf( temp.get(i).getNota() );
        }
            
        tblEspectadores.setModel(new javax.swing.table.DefaultTableModel(
            dados,
            colunas
        ));
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRecomendacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRecomendacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRecomendacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRecomendacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRecomendacoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblRecomendacao;
    private javax.swing.JTable tbmPopular;
    // End of variables declaration//GEN-END:variables
}
