/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package janelas.filme;

import classes.Filme;
import java.util.HashMap;

import sistemacatalogofilmes.SistemaCatalogoFilmes;

/**
 *
 * @author Admin
 */
public class frmMelhoresFilmes extends javax.swing.JFrame {

    /**
     * Creates new form frmMelhoresFilmes
     */
    public frmMelhoresFilmes() {
        initComponents();
        
        // Com a capacidade inicial ajustada para não precisar realocar elementos
        HashMap<Filme, Integer[]> hmFilmes = new HashMap<>(SistemaCatalogoFilmes.filmes.size() + 10, 1);
        int i;
        
        // Acumula todas as notas
        for ( i=0; i < SistemaCatalogoFilmes.bancoNotas.size(); i++ ) {
            Integer[] nota;
            // Filme ainda não foi adicionado, cria o vetor de notas
            if ( !hmFilmes.containsKey( SistemaCatalogoFilmes.bancoNotas.get(i).getFilme() ) ) {
                nota = new Integer[2];
                nota[0] = 0; // Quantidade de notas
                nota[1] = 0; // Soma das notas
                
                hmFilmes.put(SistemaCatalogoFilmes.bancoNotas.get(i).getFilme(), nota);
            }
            
            nota = hmFilmes.remove(SistemaCatalogoFilmes.bancoNotas.get(i).getFilme());
            nota[0] += 1;
            nota[1] += SistemaCatalogoFilmes.bancoNotas.get(i).getNota();
            
            hmFilmes.put(SistemaCatalogoFilmes.bancoNotas.get(i).getFilme(), nota);
        }
            
        // Calcula as médias e separo os melhores avaliados
        int MAX_MELHORES = 10;
        String[][] melhoresFilmes = new String[MAX_MELHORES][2];
        int cont = -1;
        for ( i=0; i < SistemaCatalogoFilmes.filmes.size(); i++ ) {
            Integer[] notas = hmFilmes.get(SistemaCatalogoFilmes.filmes.get(i)); 
            float media;
            
            if ( notas == null )
                continue;
            
            media = notas[1]/ (float)notas[0];
            
            if ( cont < 0 ) {
                melhoresFilmes[0][0] = SistemaCatalogoFilmes.filmes.get(i).getNome();
                melhoresFilmes[0][1] = String.valueOf(media);
                cont = 0;
            } else if ( cont+1 < MAX_MELHORES )  {
                cont++;
                melhoresFilmes[cont][0] = SistemaCatalogoFilmes.filmes.get(i).getNome();
                melhoresFilmes[cont][1] = String.valueOf(media);
            } else {
                if ( media > Float.parseFloat( melhoresFilmes[cont][1] ) ) {
                    melhoresFilmes[cont][0] = SistemaCatalogoFilmes.filmes.get(i).getNome();
                    melhoresFilmes[cont][1] = String.valueOf(media);
                }
            }
            
            // Insertion Sort,
            int j;
            for ( j = cont; j > 0; j-- ) {
                if ( Float.parseFloat( melhoresFilmes[j][1] ) >  Float.parseFloat( melhoresFilmes[j-1][1] )  ) {
                    String aux;
                    
                    // Nomes
                    aux = melhoresFilmes[j][0];
                    melhoresFilmes[j][0] = melhoresFilmes[j-1][0];
                    melhoresFilmes[j-1][0] = aux;
                    
                    // Medias
                    aux = melhoresFilmes[j][1];
                    melhoresFilmes[j][1] = melhoresFilmes[j-1][1];
                    melhoresFilmes[j-1][1] = aux;
                }
            }
            
        }
        
        String colunas[] = { "Filme", "Média" };
                    
        tblFilmes.setModel(new javax.swing.table.DefaultTableModel(
            melhoresFilmes,
            colunas
        ));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblFilmes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sistema Catálogo de Filmes (v1.0) - Melhores Filmes");

        tblFilmes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblFilmes);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel1.setText("Melhores Filmes");

        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(521, 423));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMelhoresFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMelhoresFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMelhoresFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMelhoresFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMelhoresFilmes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblFilmes;
    // End of variables declaration//GEN-END:variables
}
