/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package janelas.filme;

import classes.Filme;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

import   sistemacatalogofilmes.SistemaCatalogoFilmes;

/**
 *
 * @author Admin
 */
public class frmVerFilme extends javax.swing.JFrame {

    private int indice;
    
    /**
     * Creates new form frmVerFilme
     */
    public frmVerFilme() {
        initComponents();
        
        String codigo;
        int cod;
        
        codigo = (String)JOptionPane.showInputDialog(
                    new JFrame(),
                    "Informe o código do filme que deseja ver",
                    "Exibição de filme",
                    JOptionPane.QUESTION_MESSAGE
                );
        
        if ( codigo == "" ) {
            this.dispose();
            return;
        }
        
        // Procurar o usuário
        int total = SistemaCatalogoFilmes.filmes.size();
        indice = -1;
        int i;
        
        if ( codigo.isEmpty() || !codigo.matches("[0-9]{"+codigo.length()+"}") ) {
            JOptionPane.showMessageDialog(new JFrame(), "Preencha com um código válido!", "Mensagem", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        cod = Integer.parseInt(codigo);
        
        for( i=0; i < total; i++ ) {
            if ( SistemaCatalogoFilmes.filmes.get(i).getCodigo() == cod  ) {
                indice = i;
                break;
            }
        }
        
        if ( indice == -1 ) {
            JOptionPane.showMessageDialog(this, "Filme não encontrado!");
            this.dispose();
            return;
        }
        
        Filme filme = SistemaCatalogoFilmes.filmes.get(indice);
        lblCodigo.setText( String.valueOf( filme.getCodigo() ));
        lblNome.setText(filme.getNome());
        lblDataLancamento.setText(filme.getDataLacamento());
        lblDataDvd.setText(filme.getDataDvd());
        lblUrl.setText(filme.getUrl());
        
        lblCategorias.setText("");
        for ( i=0; i < filme.getCategorias().size(); i++) {
            lblCategorias.setText(lblCategorias.getText() + "   " + filme.getCategorias().get(i).getNome());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblDataLancamento = new javax.swing.JLabel();
        lblDataDvd = new javax.swing.JLabel();
        lblUrl = new javax.swing.JLabel();
        lblCategorias = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setText("Código");

        jLabel2.setText("Data de Lançamento");

        jLabel6.setText("Categorias");

        jLabel3.setText("Nome");

        jLabel4.setText("URL");

        jLabel5.setText("Data do DVD");

        lblCodigo.setText("__Código__");

        lblNome.setText("__Nome__");

        lblDataLancamento.setText("__Data de Lançamento__");

        lblDataDvd.setText("__Data do DVD__");

        lblUrl.setText("__URL__");

        lblCategorias.setText("__CA, te, go, ri, as__");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCodigo)
                    .addComponent(lblNome)
                    .addComponent(lblDataLancamento)
                    .addComponent(lblDataDvd)
                    .addComponent(lblUrl)
                    .addComponent(lblCategorias))
                .addContainerGap(300, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblCodigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblDataLancamento))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblDataDvd))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblUrl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblCategorias))
                .addContainerGap(157, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmVerFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmVerFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmVerFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmVerFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmVerFilme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblCategorias;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblDataDvd;
    private javax.swing.JLabel lblDataLancamento;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblUrl;
    // End of variables declaration//GEN-END:variables
}
